### ISSUE TITLE
[Functional] TaskSpace failed to automatically attach to Windows Explorer prompt

### ISSUE THREAD

**Issue by cshnik** [cshnik/TaskSpace#2]
when i open two Windows Explorers in a tab and delete file, i can not click "yes" or "no" with mouse. please check it.

**Comment by Drugoy** [comment]
The problem is more general: mouse clicks to the WinExplorer's windows sometimes just make the whole container blink and nothing else.
For example, I just tried to navigate between folders in WinExplorer window using mouse - and I got stuck on the 2nd double-click (the first one was successful): I now can't just open a folder on a disk.

The problem is not only related to double clicks: I've used RMB (right mouse button) click on the folder to open context menu (success) and then clicked on "Open" menuitem there (fail).

Plus, some clicks invoke blinking of that window on taskbar.

**Comment by cshnik** [comment]
Originally specified issue was fixed in v0.1.5.3.
I was unable to reproduce the following problems. Probably, we need to track it somehow and open new issue if the problem remains after v0.1.5.3-release.
I'll mark this issue as "Need to check" not to lose it.
