### ISSUE TITLE
[IDEA] Create toolbar with helpful commands

### ISSUE THREAD

**Issue by cshnik** [cshnik/TaskSpace#23]
I have some thoughts about implementation of specific tools/commands related to TaskSpace container and children windows. I already see some profit from these ones:
- one-click screenshot (save encoded file to disk)
- one-click screenshot editor: freezes the taskspace's content as image, enables drawing with simple tools over this snapshot, exports image to file
- cursor manager: shows cursor's coordinates and destination color (RGB)
- magnifier tool: zoom in/out for part of taskspace

**Comment by Drugoy** [comment]
None of the proposed functionality is anyhow related to grouping windows into a tabbed container.
So why encumber the util with the features that are not anyhow related to the util's main function?
Please, keep in mind that it's quite easy to ruin a good util by making a swiss knife out of it.

The era of combine-programs had already passed.
Everyone now follows the linux way (the smart way): 1 util for 1 function.

And if you think your program needs extra functions - make it modular as much as possible (the kernel without any modules should be able to only carry out the main function in the most simple way) and release modules providing extra functions.

In this case, users would be always give a choice to switch off the functionality they don't need.

I highly recommend you to go this way, if you see big future for your any program.
Also, usually bursting on multiple tasks slows down the development process of the main one.

At the current moment the program is not stable much and I think that at the moment it's more important to focus on fixing bugs and providing features related to the util's main function.

There are tons of fast screenshooters, screenshooters with editors, editors that show selected pixel's position and color and lots of magnifiers. If someone has a need in magnifier (say, due to poor vision) - they already use one and don't need another, don't you think so?
