### ISSUE TITLE
[FR] Provide an option to save settings into a file, rather than to Windows registry

### ISSUE THREAD

**Issue by Drugoy** [cshnik/TaskSpace#39]
I love everything as much portable, as possible. This program doesn't have any objective needs to be non-portable. It should store nothing in the registry.
Or at least there should be an option to not touch registry at all.

**Comment by cshnik** [comment]
"Autorun" - is the only option which requires registry editing. All the other options are always stored in the local file SETTINGS.XML.
I think I could replace the prompt with the popup hint in the system tray area(with details on this error) to not to confuse user with this registry access issue. This will allow user to understand the problem is not as much serious as it looks like now.

**Comment by Drugoy** [comment]
Oh, ok.
As for registry and autorun: why not use another place for that? just add taskspace's .lnk (a shortcut) file to the %AppData%\Roaming\Microsoft\Windows\Start Menu\Programs\ and that would do.
This doesn't require windows registry access.

**Comment by cshnik** [comment]
Good point. Thank you!

**Comment by cshnik** [comment]
Fixed in 0.3.0.0.
